package com.expense.Contants;

public class constant {
 public static String JSON_URL="[\n" +
         "\n" +
         "{\"name\" : \"AXIS_BANK\" }, {\n" +
         "\"name\" : \"BANK_OF_AMERICA\" }, {\n" +
         "\"name\" : \"BAN_BANK\" }, {\n" +
         "\"name\" : \"THE_ANDHRA_PRADESH_STATE_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_NASIK_MERCHANTS_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"APNA_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"AUSTRALIA_AND_NEW_ZEALAND_BANKING_GROUP_LIMITED\" }, {\n" +
         "\"name\" : \"CAPITAL_SMALL_FINANCE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"BANK_OF_MAHARASHTRA\" }, {\n" +
         "\"name\" : \"JALGAON_JANATA_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"JANATA_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"KALLAPPANNA_AWADE_ICHALKARANJI_JANATA_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_MUMBAI_DISTRICT_CENTRAL_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"PRIME_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_THANE_BHARAT_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_AP_MAHESH_COOPERATIVE_URBAN_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"BANK_OF_TOKYO_MITSUBISHI_LIMITED\" }, {\n" +
         "\"name\" : \"THE_GUJARAT_STATE_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"KARNATAKA_VIKAS_GRAMEENA_BANK\" }, {\n" +
         "\"name\" : \"THE_MUNICIPAL_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"NAGPUR_NAGARIK_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_KANGRA_CENTRAL_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_RAJASTHAN_STATE_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_SURAT_DISTRICT_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_VISHWESHWAR_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"WOORI_BANK\" }, {\n" +
         "\"name\" : \"SUTEX_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"BARCLAYS_BANK\" }, {\n" +
         "\"name\" : \"GURGAON_GRAMIN_BANK\" }, {\n" +
         "\"name\" : \"COMMONWEALTH_BANK_OF_AUSTRALIA\" }, {\n" +
         "\"name\" : \"PRATHAMA_BANK\" }, {\n" +
         "\"name\" : \"NORTH_MALABAR_GRAMIN_BANK\" }, {\n" +
         "\"name\" : \"THE_VARACHHA_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"SBER_BANK\" }, {\n" +
         "\"name\" : \"TUMKUR_GRAIN_MERCHANTS_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"VASAI_VIKAS_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"VASAI_VIKAS_SAHAKARI_BANK_LTD\" }, {\n" +
         "\"name\" : \"BASSEIN_CATHOLIC_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"WESTPAC_BANKING_CORPORATION\" }, {\n" +
         "\"name\" : \"ANDHRA_PRAGATHI_GRAMEENA_BANK\" }, {\n" +
         "\"name\" : \"SUMITOMO_MITSUI_BANKING_CORPORATION\" }, {\n" +
         "\"name\" : \"THE_SEVA_VIKAS_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_THANE_DISTRICT_CENTRAL_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"JP_MORGAN_BANK\" }, {\n" +
         "\"name\" : \"THE_GADCHIROLI_DISTRICT_CENTRAL_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_AKOLA_DISTRICT_CENTRAL_COOPERATIVE_BANK\" }, {\n" +
         "\"name\" : \"THE_KURMANCHAL_NAGAR_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_JALGAON_PEOPELS_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"PARIBAS\" }, {\n" +
         "\"name\" : \"NATIONAL_AUSTRALIA_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"SAHEBRAO_DESHMUKH_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"BANK_INTERNASIONAL_INDONESIA\" }, {\n" +
         "\"name\" : \"SOLAPUR_JANATA_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"INDUSTRIAL_AND_COMMERCIAL_BANK_OF_CHINA_LIMITED\" }, {\n" +
         "\"name\" : \"UNITED_OVERSEAS_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"ZILA_SAHAKRI_BANK_LIMITED_GHAZIABAD\" }, {\n" +
         "\"name\" : \"JANASEVA_SAHAKARI_BANK_BORIVLI_LIMITED\" }, {\n" +
         "\"name\" : \"RAJGURUNAGAR_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"CANARA_BANK\" }, {\n" +
         "\"name\" : \"NAGAR_URBAN_CO_OPERATIVE_BANK\" }, {\n" +
         "\"name\" : \"AKOLA_JANATA_COMMERCIAL_COOPERATIVE_BANK\" }, {\n" +
         "\"name\" : \"BHARATIYA_MAHILA_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"HSBC_BANK_OMAN_SAOG\" }, {\n" +
         "\"name\" : \"THE_KANGRA_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_ZOROASTRIAN_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"SHIKSHAK_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_HASTI_COOP_BANK_LTD\" }, {\n" +
         "\"name\" : \"CATHOLIC_SYRIAN_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"KERALA_GRAMIN_BANK\" }, {\n" +
         "\"name\" : \"PRAGATHI_KRISHNA_GRAMIN_BANK\" }, {\n" +
         "\"name\" : \"DEPOSIT_INSURANCE_AND_CREDIT_GUARANTEE_CORPORATION\" }, {\n" +
         "\"name\" : \"DEVELOPMENT_BANK_OF_SINGAPORE\" }, {\n" +
         "\"name\" : \"DOHA_BANK\" }, {\n" +
         "\"name\" : \"DOHA_BANK_QSC\" }, {\n" +
         "\"name\" : \"EXPORT_IMPORT_BANK_OF_INDIA\" }, {\n" +
         "\"name\" : \"JANAKALYAN_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"TJSB_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"TJSB_SAHAKARI_BANK_LTD\" }, {\n" +
         "\"name\" : \"THE_COSMOS_CO_OPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"SURAT_NATIONAL_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"CENTRAL_BANK_OF_INDIA\" }, {\n" +
         "\"name\" : \"IDFC_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"INDUSTRIAL_BANK_OF_KOREA\" }, {\n" +
         "\"name\" : \"SBM_BANK_MAURITIUS_LIMITED\" }, {\n" +
         "\"name\" : \"NATIONAL_BANK_OF_ABU_DHABI_PJSC\" }, {\n" +
         "\"name\" : \"KEB_HANA_BANK\" }, {\n" +
         "\"name\" : \"THE_PANDHARPUR_URBAN_CO_OP_BANK_LTD_PANDHARPUR\" }, {\n" +
         "\"name\" : \"SAMARTH_SAHAKARI_BANK_LTD\" }, {\n" +
         "\"name\" : \"SHIVALIK_MERCANTILE_CO_OPERATIVE_BANK_LTD\" }, {\n" +
         "\"name\" : \"HIMACHAL_PRADESH_STATE_COOPERATIVE_BANK_LTD\" }, {\n" +
         "\"name\" : \"DEOGIRI_NAGARI_SAHAKARI_BANK_LTD_AURANGABAD\" }, {\n" +
         "\"name\" : \"CHINATRUST_COMMERCIAL_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"PT_BANK_MAYBANK_INDONESIA_TBK\" }, {\n" +
         "\"name\" : \"MAHARASHTRA_GRAMIN_BANK\" }, {\n" +
         "\"name\" : \"EQUITAS_SMALL_FINANCE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"AIRTEL_PAYMENTS_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"CITI_BANK\" }, {\n" +
         "\"name\" : \"CITIZEN_CREDIT_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"CITY_UNION_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"CORPORATION_BANK\" }, {\n" +
         "\"name\" : \"CREDIT_AGRICOLE_CORPORATE_AND_INVESTMENT_BANK_CALYON_BANK\" }, {\n" +
         "\"name\" : \"DENA_BANK\" }, {\n" +
         "\"name\" : \"DEUSTCHE_BANK\" }, {\n" +
         "\"name\" : \"DCB_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"DHANALAKSHMI_BANK\" }, {\n" +
         "\"name\" : \"DOMBIVLI_NAGARI_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"FIRSTRAND_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"HDFC_BANK\" }, {\n" +
         "\"name\" : \"HSBC_BANK\" }, {\n" +
         "\"name\" : \"ICICI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"IDBI_BANK\" }, {\n" +
         "\"name\" : \"INDIAN_BANK\" }, {\n" +
         "\"name\" : \"INDIAN_OVERSEAS_BANK\" }, {\n" +
         "\"name\" : \"INDUSIND_BANK\" }, {\n" +
         "\"name\" : \"JANASEVA_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"KAPOL_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"KARNATAKA_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"KARUR_VYSYA_BANK\" }, {\n" +
         "\"name\" : \"KOTAK_MAHINDRA_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"MAHANAGAR_COOPERATIVE_BANK\" }, {\n" +
         "\"name\" : \"MAHARASHTRA_STATE_COOPERATIVE_BANK\" }, {\n" +
         "\"name\" : \"MASHREQBANK_PSC\" }, {\n" +
         "\"name\" : \"MIZUHO_BANK_LTD\" }, {\n" +
         "\"name\" : \"NEW_INDIA_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"NKGSB_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"NUTAN_NAGARIK_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"ORIENTAL_BANK_OF_COMMERCE\" }, {\n" +
         "\"name\" : \"PARSIK_BANK\" }, {\n" +
         "\"name\" : \"PUNJAB_AND_MAHARSHTRA_COOPERATIVE_BANK\" }, {\n" +
         "\"name\" : \"PUNJAB_AND_SIND_BANK\" }, {\n" +
         "\"name\" : \"PUNJAB_NATIONAL_BANK\" }, {\n" +
         "\"name\" : \"RAJKOT_NAGRIK_SAHAKARI_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"RESERVE_BANK_OF_INDIA\" }, {\n" +
         "\"name\" : \"SHINHAN_BANK\" }, {\n" +
         "\"name\" : \"SOCIETE_GENERALE\" }, {\n" +
         "\"name\" : \"SOUTH_INDIAN_BANK\" }, {\n" +
         "\"name\" : \"STANDARD_CHARTERED_BANK\" }, {\n" +
         "\"name\" : \"STATE_BANK_OF_BIKANER_AND_JAIPUR\" }, {\n" +
         "\"name\" : \"STATE_BANK_OF_HYDERABAD\" }, {\n" +
         "\"name\" : \"STATE_BANK_OF_INDIA\" }, {\n" +
         "\"name\" : \"STATE_BANK_OF_MAURITIUS_LIMITED\" }, {\n" +
         "\"name\" : \"STATE_BANK_OF_MYSORE\" }, {\n" +
         "\"name\" : \"STATE_BANK_OF_PATIALA\" }, {\n" +
         "\"name\" : \"STATE_BANK_OF_TRAVANCORE\" }, {\n" +
         "\"name\" : \"SYNDICATE_BANK\" }, {\n" +
         "\"name\" : \"TAMILNAD_MERCANTILE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_BANK_OF_NOVA_SCOTIA\" }, {\n" +
         "\"name\" : \"AHMEDABAD_MERCANTILE_COOPERATIVE_BANK\" }, {\n" +
         "\"name\" : \"BHARAT_COOPERATIVE_BANK_MUMBAI_LIMITED\" }, {\n" +
         "\"name\" : \"FEDERAL_BANK\" }, {\n" +
         "\"name\" : \"THE_GREATER_BOMBAY_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"JAMMU_AND_KASHMIR_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"KALUPUR_COMMERCIAL_COOPERATIVE_BANK\" }, {\n" +
         "\"name\" : \"THE_KARANATAKA_STATE_COOPERATIVE_APEX_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"KALYAN_JANATA_SAHAKARI_BANK\" }, {\n" +
         "\"name\" : \"LAXMI_VILAS_BANK\" }, {\n" +
         "\"name\" : \"ESAF_BANK\" }, {\n" +
         "\"name\" : \"THE_MEHSANA_URBAN_COOPERATIVE_BANK\" }, {\n" +
         "\"name\" : \"THE_NAINITAL_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"RBL_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_ROYAL_BANK_OF_SCOTLAND\" }, {\n" +
         "\"name\" : \"SARASWAT_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_SHAMRAO_VITHAL_COOPERATIVE_BANK\" }, {\n" +
         "\"name\" : \"THE_SURATH_PEOPLES_COOPERATIVE_BANK_LIMITED\" }, {\n" +
         "\"name\" : \"THE_TAMIL_NADU_STATE_APEX_COOPERATIVE_BANK\" }, {\n" +
         "\"name\" : \"THE_WEST_BENGAL_STATE_COOPERATIVE_BANK\" }, {\n" +
         "\"name\" : \"UCO_BANK\" }, {\n" +
         "\"name\" : \"UNION_BANK_OF_INDIA\" }, {\n" +
         "\"name\" : \"UNITED_BANK_OF_INDIA\" }, {\n" +
         "\"name\" : \"VIJAYA_BANK\" }\n" +
         "\n" +
         "]\n";
}